name: flutter_manejo_estado
description: Base para una aplicacion Flutter con arquitectura limpia.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_riverpod: ^3.4.3
  shared_preferences: ^2.5.3

flutter:
  uses-material-design: true